# Funding options for this project
# These are supported funding model platforms

github: # Add GitHub Sponsors username here if available
patreon: # Add Patreon username here if available
ko_fi: # Add Ko-fi username here if available
custom: # Add custom sponsorship URL here if available
